# Generated by Django 4.1.13 on 2024-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('portal_name', models.CharField(default=None, max_length=256, null=True)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'db_table': 'engine_team',
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('external_id', 'portal_name')},
            },
        ),
    ]
