# Generated by Django 4.1.13 on 2024-06-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_document', '0002_teamdocument_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdocument',
            name='type',
            field=models.CharField(default='file', max_length=256),
        ),
    ]
