_base_model: &base_model
    base: id_resource
    key: id
    admin_roles: [data-admin]
    view_roles: [data-auditor]
    priority: 60

models:
    team:
        <<: *base_model
        plural: teams
        key: id
        id_fields: [external_id, portal_name]
        display: "<portal_name>:<external_id>"
        priority: 60
        fields:
            portal_name:
                type: string
            external_id:
                type: string

    team_document_collection:
        <<: *base_model
        base: team
        plural: team_document_collections
        id_fields: [team, external_id]
        key: external_id
        display: "<external_id>: <name>"
        priority: 70
        fields:
            external_id:
                type: string

    team_document:
        <<: *base_model
        base: team_document_collection
        plural: team_documents
        id_fields: [team_document_collection, external_id]
        key: id
        display: "<id>: <hash>"
        priority: 75
        fields:
            external_id:
                type: string
            hash:
                type: string
                options:
                    max_length: 65
            text:
                type: text
            sentences:
                type: list
            topics:
                type: dict

    team_project:
        <<: *base_model
        base: team
        mixins: [team_document_collections]
        plural: team_projects
        id_fields: [team, external_id]
        key: external_id
        display: "<external_id>: <name>"
        priority: 65
        fields:
            external_id:
                type: string
            summary_model:
                type: string
            summary_persona:
                type: string
            summary_format:
                type: string
            temperature:
                type: float
            top_p:
                type: float
            repetition_penalty:
                type: float
