# Generated by Django 4.1.13 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project', '0002_teamproject_team_document_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='repetition_penalty',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='temperature',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='top_p',
            field=models.FloatField(default=None, null=True),
        ),
    ]
