# Generated by Django 4.1.13 on 2024-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project', '0005_teamproject_access_teams_teamproject_team_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='team_projects',
            field=models.ManyToManyField(blank=True, related_name='+', to='team_project.teamproject'),
        ),
    ]
