# Generated by Django 4.1.13 on 2024-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project', '0006_teamproject_team_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='summary_prompt_model',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='teamproject',
            name='summary_topic_model',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
