# Generated by Django 4.1.13 on 2024-05-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDocumentCollection',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(data_name)s', to='team.team')),
            ],
            options={
                'verbose_name': 'team document collection',
                'verbose_name_plural': 'team document collections',
                'db_table': 'engine_team_document_collection',
                'ordering': ['external_id'],
                'abstract': False,
                'unique_together': {('team', 'external_id')},
            },
        ),
    ]
