# Generated by Django 4.1.13 on 2024-07-07 19:53

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team_document_collection', '0002_teamdocumentcollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdocumentcollection',
            name='access_teams',
            field=systems.models.fields.ListField(default=list),
        ),
    ]
